### ISSUE TITLE
Private repository does not work

### ISSUE THREAD

**Issue by cbou** [rhysd/changelog-from-release#1]
I have trouble running this program on private repository. I get this error `Error: Cannot get releases from repository`.

Even adding a Github Token to `$GITHUB_TOKEN` does not help.

**Comment by rhysd** [comment]
What permission did you give the token? Without giving proper permission, it does not work.

**Comment by cbou** [comment]
I give this permissions.
<img width="466" alt="screenshot 2019-03-04 at 20 29 04" src="https://user-images.githubusercontent.com/611389/53757535-337b4080-3ebc-11e9-8242-7b7e341811e5.png">

**Comment by rhysd** [comment]
Your setup looks good. Well, let me check this on my side.

**Comment by rhysd** [comment]
I confirmed following steps work fine:

1. Generate personal access token with 'repo' permission
2. Set it to environment variable by `export GITHUB_TOKEN=xxxxxxxxxx`
3. Run `changelog-from-release` in private repository directory
4. Confirm `CHANGELOG.md` is generated and it contains releases page contents

**Comment by DavidCannon** [comment]
I'm experiencing the same error as the OP when trying to use your tool as a GitHub Action on my private repo. I've setup a personal access token with repo permissions. I then added a new secret in my repo settings titled 'secrets.ACTIONS_TOKEN' with that personal access token as the value. But when I post a release and the action runs, it fails on this step:

`Run rhysd/changelog-from-release/action@v2`

With the following...

```
Run rhysd/changelog-from-release/action@v2
/usr/bin/docker run --name e4032e435f149b4c569e828c56674284ca_986d31 --label 5588e4 --workdir /github/workspace --rm -e INPUT_FILE -e INPUT_GITHUB-TOKEN -e INPUT_VERSION -e INPUT_COMMIT -e INPUT_PUSH -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/<repo>":"/github/workspace" <id>
changelog-from-release version: v2.2.0
+ GITHUB_TOKEN= /changelog-from-release
Error: Cannot get releases from repository <repo> via GitHub API: GET https://api.github.com/repos/<repo>/releases: 404 Not Found []
```

Any help you can give would be greatly appreciated. Your action is exactly what I was wanting, if I can just get it to work. 😃
