### ISSUE TITLE
feature request: list releases with second level headings

### ISSUE THREAD

**Issue by giocaizzi** [rhysd/changelog-from-release#14]
It would be amazing if there was a feature (possibly called with a command line argument) that would list releases as second level headings, possibly prepended by something like a "# Changelog" first level heading.

It would be useful when including the .md file in an index, without having all single releases showing up in the toctree.

I would contribute myself, but unfortunately i know very little of Go. Do you think this is worth implementing? Thanks 🚀

**Comment by rhysd** [comment]
> Do you think this is worth implementing?

GitHub provides Markdown ToC in web UI. Personally it's sufficient for me. What is your use case?

https://github.blog/changelog/2021-04-13-table-of-contents-support-in-markdown-files/

> I would contribute myself, but unfortunately i know very little of Go.

This feature would be easy for me. Once I understand reasonable use case, I would be able to implement it soon.

**Comment by giocaizzi** [comment]
My use case is that I am using Sphinx to build a static html website for the documentation of a Python package. Without this feature the whole list of H1 headings would end up as being elements of the main table of contents of the website. Whereas being H2, they are not.

I have seen that you have already implemented it. Thanks 🚀

**Comment by rhysd** [comment]
I see. That looks nice use case to me. I'll consider to add an option to generate ToC.

**Comment by rhysd** [comment]
@giocaizzi 

At b0badff, I added `-t` flag. Running the following commands in this repository

```sh
cat <<-EOS > test.md
CHANGELOG
=========

## Releases

EOS

changelog-from-release -l 2 -t >> test.md
```

generates the following output:

https://gist.github.com/rhysd/186a723397431906d9491ab196143d04

Does it look good to you? I wonder date of release should be included in list item like `- [v1.2.3](#v1.2.3) - Aug 26`.

**Comment by rhysd** [comment]
I may misunderstand your use case. Is the ToC list generated by Sphinx (so it is not necessary to be done by changelog-from-release)?

**Comment by giocaizzi** [comment]
Yes, the ToC is defined within Sphinx, so I just needed the possibility to choose the heading level. 


With the last changes at #b0badff it will be possible to set the main title. Great, thanks!

**Comment by rhysd** [comment]
OK, thank you for the clarification. I'll revert the commit and close this issue.
