### ISSUE TITLE
Github actions failed when the branch protection is on

### ISSUE THREAD

**Issue by FUTURETECH6** [rhysd/changelog-from-release#17]
I have turned branch protection on (only `Require a pull request before merging` and `Require approvals`) for my repo, and when I run the actions, it failed with the output:

```
+ git push --force ***github.com/user/repo.git
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: At least 1 approving review is required by reviewers with write access.        
To https://github.com/user/repo.git
 ! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/user/repo.git'
```

There is no reason this would fail since it's a *push* rather than a *pr*. After I disable the branch protection, the CHANGELOG.md can be generated.

**Comment by rhysd** [comment]
Correct. The action does not support protected branch for now. I think it should have option to make a PR instead of pushing commit.

**Comment by rhysd** [comment]
I added `pull_requst` input to the action at 0d91b80.

Here is a demo of pull request automatically submitted: https://github.com/rhysd/changelog-from-release/pull/18

I'll make a new release soon.
