### ISSUE TITLE
Version 3.5.2 and up causes a 404 error

### ISSUE THREAD

**Issue by Kahera** [rhysd/changelog-from-release#19]
Starting at version 3.5.2, I get the following error: 
![image](https://user-images.githubusercontent.com/44864244/212659865-8cb881b1-1b3b-4e14-b2a7-e3173ab2b050.png)

Downgrading back to 3.5.1 makes the action work as expected again: 
![image](https://user-images.githubusercontent.com/44864244/212660499-ec5369b5-f326-4c2b-897e-a7f39f15dbbd.png)

For reference in case it's useful, the workflow is set up in the following way: 
- Checkout (actions/checkout@v3)
- Create new branch (peterjgrainger/action-create-branch@v2.4.0)
- Checkout to new branch (actions/checkout@v3)
- Generate changelog

(The workflow was naturally created before the PR-option for this action was avaliable, which is the reasoning for the branching).

**Comment by rhysd** [comment]
@Kahera Thanks for reporting this. Is it a private repository?

**Comment by Kahera** [comment]
@rhysd Yes, it is.

**Comment by rhysd** [comment]
Please try the latest version 3.6.1.

https://github.com/rhysd/changelog-from-release/releases/tag/v3.6.1

**Comment by Kahera** [comment]
That works - thank you for the quick fix! 🥳
