### ISSUE TITLE
Disable automatic tag addition to title

### ISSUE THREAD

**Issue by udenr** [rhysd/changelog-from-release#20]
We started using this automation in some of our projects and noticed that after the release title there is always the tag. But since we already have the version number in the release title anyway, it is now twice in a row. e.g. [Minesweeper (Privacy Friendly) v1.2.0 (v1.2.0)](https://github.com/SecUSo/privacy-friendly-minesweeper/blob/80127cde26f2e97495484b428fdf518f36559de8/CHANGELOG.md).

Is it possible to turn off the automatic addition of the tag or leave the tag out if it is already in the title? It's only a minor inconvenience, but would be great if that would be possible.

**Comment by rhysd** [comment]
Yes, that's possible by adding new flag. However, isn't it sufficient to remove the version from the title like `Minesweeper (Privacy Friendly)`?

**Comment by rhysd** [comment]
v3.7.0 fixed this.

https://github.com/rhysd/changelog-from-release/releases/tag/v3.7.0

**Comment by udenr** [comment]
Thank you for the quick fix!
