### ISSUE TITLE
403 error with the Action

### ISSUE THREAD

**Issue by nhoizey** [rhysd/changelog-from-release#21]
I'm trying to use the Action on https://github.com/nhoizey/eleventy-plugin-pack11ty

The changelog file is generated, but I get a 403 error when the Action tries to push the result.

Here's the end of the Action log (without the file content):

```shell
+ GITHUB_TOKEN=*** /changelog-from-release
changelog-from-release version: v3.7.0
+ CHANGELOG='…'
+ set +x
+ '[' false '=' true ]
+ git add CHANGELOG.md
+ git -c 'user.name=nhoizey' -c 'user.email=nhoizey@users.noreply.github.com' commit -m 'Update changelog for "v1.7.1"

    This commit was created by changelog-from-release in '"'"'Update CHANGELOG'"'"' CI workflow'
+ '[' true '=' true ]
+ git push --force ***github.com/nhoizey/eleventy-plugin-pack11ty.git
 1 file changed, 155 insertions(+)
 create mode 100644 CHANGELOG.md
remote: Permission to nhoizey/eleventy-plugin-pack11ty.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/nhoizey/eleventy-plugin-pack11ty.git/': The requested URL returned error: 403
```

Here's the workflow: https://github.com/nhoizey/eleventy-plugin-pack11ty/blob/main/.github/workflows/changelog-from-release.yml

**Comment by rhysd** [comment]
Hmm... [This workflow](https://github.com/rhysd/changelog-from-release/blob/master/.github/workflows/post-release.yml) run [successfully](https://github.com/rhysd/changelog-from-release/actions/runs/4036660873/jobs/6939419032) 3 months ago. I don't know why. There may be some change in GitHub side.

**Comment by nhoizey** [comment]
I still have the issue, and couldn't find how to fix it.

Are you still using it somewhere and it still works?

**Comment by rhysd** [comment]
Yes. This repository uses itself to update changelog. It ran without errors 17 days ago.

https://github.com/rhysd/changelog-from-release/actions/runs/7667731470

Do you use a protected branch? The repository may reject push due to it.

**Comment by nhoizey** [comment]
Thanks, good to know it still works, the issue is on my side.

I use a protected branch, changed the action to use a Pull Request, but it still doesn't work.

**Comment by nhoizey** [comment]
I finally managed to make it work with a PR.
