### ISSUE TITLE
Update changelog before adding the release tag in Github action.

### ISSUE THREAD

**Issue by Kieun** [rhysd/changelog-from-release#22]
In FAQ section of README, there is a description the way `how to update changelog before adding the release tag`.

I'm trying to do such things with Github actions, but it seems that there is no such features at this moment.
Am I correct? If so, it would be great to have a such feature.

**Comment by rhysd** [comment]
You can create a new release as draft even if Git tag is not created yet for it.

**Comment by Kieun** [comment]
> You can create a new release as draft even if Git tag is not created yet for it.

@rhysd  my intention is that,

1.  Create draft release note with tag
2. Github action catch the event, and it generates change log with the draft release note
3. Github action push the change log with the tag (which is define din the draft release note)
4. Public release note (manually in github menu)

Is this possible as it is?
