### ISSUE TITLE
Feature request: use ISO date

### ISSUE THREAD

**Issue by FloEdelmann** [rhysd/changelog-from-release#27]
Currently, dates in the generated Markdown file look like this: `25 Apr 2021`
It would be great to have an option to change this to the [ISO date format](https://www.iso.org/iso-8601-date-and-time-format.html), e.g. `2021-04-25`.

See also https://keepachangelog.com/en/1.1.0/ and https://common-changelog.org/, where this is also recommended.

**Comment by rhysd** [comment]
I'm thinking about adding a capability to customize release note format using [`text/template`](https://pkg.go.dev/text/template).
