### ISSUE TITLE
Add a text-only option

### ISSUE THREAD

**Issue by ricardoboss** [rhysd/changelog-from-release#29]
Hi! We've recently started using the action to generate release notes from GitHub Releases in https://github.com/std-uritemplate/std-uritemplate.

I seems to be working fine, but some packages we publish don't support rendering Markdown/HTML in the CHANGELOG (see https://github.com/std-uritemplate/std-uritemplate/issues/219).

Would it be possible to add a mode that only generates text, without links, comments or any structural elements at all?

**Comment by rhysd** [comment]
I considered this feature but I don't think it is needed for this tool. You can convert the generated Markdown file into a plain text. I would recommend using [Pandoc](https://pandoc.org/).

```sh
pandoc CHANGELOG.md -t plain -o CHANGELOG.txt
```

**Comment by rhysd** [comment]
[CHANGELOG.txt](https://github.com/user-attachments/files/17444713/CHANGELOG.txt)

Here is an example of the plain text converted from [CHANGELOG.md](https://github.com/rhysd/changelog-from-release/blob/master/CHANGELOG.md). Conversion looks working nicely to me.

**Comment by rhysd** [comment]
Closing as `pandoc` is a solution.
