### ISSUE TITLE
No output after waiting several minutes

### ISSUE THREAD

**Issue by paul-uz** [rhysd/changelog-from-release#8]
I am running the GO binary whilst inside a private repo. I exported a github token, with the correct permissions.

`../../../go/bin/changelog-from-release > CHANGELOG.md`

The MD file is created, but after waiting several minutes, nothing is happening, with the program seemingly hanging?

No errors etc are output in the console, so I'm not sure what's going on.

**Comment by KoduIsGreat** [comment]
I'm having a similar issue, this issue is still pretty old @rhysd are you still maintaing this?

**Comment by rhysd** [comment]
[v2.2.5](https://github.com/rhysd/changelog-from-release/releases/tag/v2.2.5) would fix this issue. Please try the latest version.
